name: bible
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BIBLE_BOOK: sl
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: setup
        run: |
          git config --global user.name 'arthur-bot'
          git config --global user.email 'arthur393@gmail.com'
          mkdir -p bible/${BIBLE_BOOK}
      
      - name: search gospel
        run: |
          ./bible/main.sh
      
      - name: write ref
        run: |
          echo "- [${BIBLE_BOOK} day_$(date "+%d")](bible/${BIBLE_BOOK}/day_$(date "+%d"))" >> README.md
             
      - name: commit
        run: |
          git add bible/${BIBLE_BOOK}/day_$(date "+%d") README.md
          git commit -m "ready message prepared for you at: day_$(date "+%d")"

      - name: push
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}